spring:
  application:
    name: euraka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://ocalhost:7900/eureka/,http://ocalhost:7901/eureka/,http://ocalhost:7902/eureka/

---
spring:
  profiles: 7901
eureka:
  instance:
    hostname: eureka-7901
server:
  port: 7901

---
spring:
  profiles: 7902
eureka:
  instance:
    hostname: eureka-7902
server:
  port: 7902

---
spring:
  profiles: 7900
eureka:
  instance:
    hostname: eureka-7900
server:
  port: 7900